# Generated by Django 2.2.2 on 2019-07-06 23:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Study', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='studythread',
            old_name='op',
            new_name='user',
        ),
        migrations.AddField(
            model_name='studythread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='StudyThreadVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('study_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Study.StudyThread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyCommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('study_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Study.StudyComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
